### ISSUE TITLE
Determine if new occulter responsible for dark band in images on March, 30 2024

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/kcor-pipeline#386]
We see some strange behavior in KCor on the eclipse prep day.

In the morning, the data looked OK, and then, after calibration, a dark near-vertical band appeared in the data (NRGF). This band looks to be related to the optics moves we see during a calibration sequence. And it appears to be gone on April 9th.

Before:

![20240330_221459_kcor_l2_nrgf](https://github.com/user-attachments/assets/f59a9cd4-bdb6-436b-b437-4647d798e2a3)

Toward the end of the Cal:

![20240330_223058_kcor_l2_nrgf](https://github.com/user-attachments/assets/bf7b7cf2-e8ba-4943-b760-1a2299e442ad)

Post Cal:

![20240330_223058_kcor_l2_nrgf_avg](https://github.com/user-attachments/assets/7eead694-1590-4317-9add-ffa9955403d5)

#### Tasks

- [x] remove 20240330 cal file and reprocess 20240330 using the 20240409 cal sequence
- [x] add a new cal epoch right after the cal sequence on 20240330

#### Summary

These data cannot be fixed. There is an obstacle (cal pol optic) in the beam.

**Comment by mgalloy** [comment]
Results are in:

- `raw.20240409-cal-sequence` (all one cal epoch that will use 20240409 cal file for all data)
- `raw.split-cal-sequence` (split before cal sequence to use 20240330 cal file and after cal sequence to use 20240330 cal file)

Compare to production which would use 20240330 cal file for all data.

**Comment by bberkeyU** [comment]
@mgalloy I do not see the sequence directories in the Kcor folder.

**Comment by mgalloy** [comment]
Hang on, there was a mistake in the cal file for the split cal epochs. I'm re-running `raw.split-cal-sequence` because of that. The filename was right, but the `epoch` attribute was wrong. Checking why `raw.20240409-cal-sequence` didn't produce the files after the cal sequence now...

**Comment by mgalloy** [comment]
Ah, the `raw.20240409-cal-sequence` did produce the files after the cal sequence and they look bad.

**Comment by mgalloy** [comment]
By the way, remember the new location for data is not the normal location for results. Check the config files in my `kcor-config` directory if you don't know the locations.

**Comment by mgalloy** [comment]
`raw.20240409-cal-sequence` finished and the images after the cal sequence look bad to me. I don't see a difference between the images in these two runs and production.

**Comment by mgalloy** [comment]
From `raw.split-cal-sequence`:

![20240330_223113_kcor_l2_nrgf_avg](https://github.com/user-attachments/assets/19469edf-0190-4c8b-b471-8fb8dbd3aab9)

``` Shell
level2$ fitscat -r 20240330_223113_kcor_l2_nrgf_avg.fts.gz | grep CALFILE
CALFILE = '20240409_190118_kcor_cal_v27_2.1.15_2.500ms.ncdf' / calibration file
```

From `raw.20240409-cal-sequence`:

![20240330_223113_kcor_l2_nrgf_avg](https://github.com/user-attachments/assets/b59439c4-2e74-469a-9ff2-99ece3ab3eb6)

``` Shell
level2$ fitscat -r 20240330_223113_kcor_l2_nrgf_avg.fts.gz | grep CALFILE
CALFILE = '20240409_190118_kcor_cal_v26_2.1.15_2.500ms.ncdf' / calibration file
```

**Comment by jburkepile** [comment]
There were 2 changes that took place on March 30 after which the data have the black shadow across the images: 1) new tapered occulter installed and 2) a calibration sequence was taken.  We expect the new occulter to produce less stray light. You showed the cal file from Apr 9 with the new occulter did not fix the problem. I shouldn't be too surprised since flats do scatter the signal uniformly. That leaves the cal sequence. I am back to suspecting that the calibration optics were not fully retracted and were slightly in the beam causing vignetting that produced the black shadow. When the observers started observations on April 9 they began by putting the cal polarizer in the beam to get the right polarization sequence. My best guess is that when it was moved out of the beam it fully retracted. There were no other changes to KCor between March 30 and April 9. 
Conclusion:  These data cannot be fixed. There is an obstacle (cal pol optic) in the beam.
