### ISSUE TITLE
Verify solar north

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#73]
Might need a epoch value to that would be added to the p-angle when the images are rotated to north up.

**Comment by jburkepile** [comment]
Don and joan created composites of AIA and KCor for a handful of days in 2013-2014-2015-2016 and a few dozen days in 2017-2018. A clockwise rotation of 0.5 degrees to KCor data seems to improve the alignment with AIA. Best day was 20170910 when a sharp current sheet ray was visible on the west limb.
HOWEVER, there are days in 2018 where CW 2 deg. rotation works better for parts of the corona. One problem is that the Sun is NOT centered under the occulter. When data are rotated to north up, there will be misalignments with other solar data in some regions of the corona since we are not rotating around Sun center. This is an inherent problem produced by current pointing.

RECAP: Add a 0.5 deg. CW rotation to K-Cor.  
TEST: As data are recalibrated create occasional composites with AIA to check alignment. Is another angle needed (e.g. add epochs) at certain times in the mission?

**Comment by jburkepile** [comment]
ADD Keyword to L1.5 header to note 0.5 deg CW rotation to K-Cor:
ROLLCORR  0.5  / [deg.] CW rotation of data to correct for spar polar align.

**Comment by jburkepile** [comment]
Verified that rotation of 0.7 degrees CW aligns well with AIA and LASCO data. Some examples are shown below.
![20180101-1805_lasco-kcor-aia_composite](https://user-images.githubusercontent.com/18175973/51201242-c6363080-18b8-11e9-8e2f-4bd18e63cf66.png)

![20170910_kcor-aia193-composite_0 7cw](https://user-images.githubusercontent.com/18175973/51201607-b8cd7600-18b9-11e9-8615-271fbadb245a.png)
